name = "numsa"
version = "0.2.0"
license = "LGPL-3.0-or-later"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
description = "Numerical solvent accessible surface area calculation"
keywords = ["computational-chemistry", "quadrature", "lebedev"]
copyright = "Copyright 2021 S. Ehlert"

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib"

[dev-dependencies]
mstore.git = "https://github.com/grimme-lab/mstore"
